"""empty message

Revision ID: 1b7460f154e6
Revises: 
Create Date: 2020-03-05 21:19:29.360483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7460f154e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('async_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=120), nullable=True),
    sa.Column('document', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('day_send', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_task_receiver'), 'async_task', ['receiver'], unique=False)
    op.create_table('periodic_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=120), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('start_sent', sa.DateTime(), nullable=True),
    sa.Column('end_sent', sa.DateTime(), nullable=True),
    sa.Column('period_type', sa.String(length=120), nullable=False),
    sa.Column('period_value', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodic_task_receiver'), 'periodic_task', ['receiver'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodic_task_receiver'), table_name='periodic_task')
    op.drop_table('periodic_task')
    op.drop_index(op.f('ix_async_task_receiver'), table_name='async_task')
    op.drop_table('async_task')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('document')
    # ### end Alembic commands ###
